jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install --upgrade pip

      - run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # Change working directory to repo root
      - working-directory: ${{ github.workspace }}
        run: |
          if [ ! -f jobs.db ]; then
            echo "Creating empty jobs.db"
            python -c "import sqlite3; sqlite3.connect('jobs.db').close()"
          fi

      - working-directory: ${{ github.workspace }}
        run: python core_job_scraper.py
